version: "3.8"
services:
    frontend:
        image: httpd 
        networks:
        - front-back
        ports:
        - 5000:80    
        volumes:
        - ~/class9/web:/usr/local/apache2/htdocs
        depends_on:
        - backend

    backend:
        image: taeahmed/simple_flask_app #build:.
        networks:
        - front-back
        - back-db
        depends_on:
        - database

    database:
        image: mariadb  
        networks:
        - back-db
        ports:
        - 3306:3306
        volumes:
        - database:/var/lib/mysql
        environment: 
        - MARIADB_ROOT_PASSWORD=1234
networks:
    front-back:
    back-db:
volumes:
    database:
